155 update migration doc
metricq/metricq-python pull request #161
Opened 2023-04-13 08:00 UTC by tilsche

2023-04-13 15:11 UTC, tilsche commented
Got a bigger as I started cleaning up warnings while adding the migration guideline.

2023-04-14 08:47 UTC, bmario requested changes

2023-04-14 08:47 UTC, bmario commented on metricq/synchronous_source.py
> +            metrics: a mapping from metric name to metadata
The type of that parameter should be `Mapping[Metric, MetadataDict]`

2023-04-14 08:47 UTC, bmario commented on metricq/synchronous_source.py
> +    Therefore, it this class does not actually derive from :class:`Source`.
```suggestion
    Therefore, this class does not actually derive from :class:`Source`.
```

2023-04-14 08:47 UTC, bmario commented on docs/howto/sink.rst
> +Further, you need to implement a RPC handler for `config`.
```suggestion
Further, you need to implement an RPC handler for `config`.
```

2023-04-14 08:47 UTC, bmario commented on docs/api/sink.rst
> +
```suggestion

----
```

2023-04-14 11:49 UTC, merged